theme = "hugo-tailwindcss-starter-theme"
languageCode = "en-us"
baseurl = "http://example.com/"
title = "New Tailwind Theme"

copyright = "Copyright © 2023, Luca Palonca, all rights reserved."

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Home"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "About"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "Products"
    url     = "products"
    weight  = 3
  [[menu.nav]]
    name    = "Blog"
    url     = "blog"
    weight  = 4
  [[menu.nav]]
    name    = "Get in touch"
    url     = "contact"
    weight  = 5


[params]
    logo = "images/generic-logo.png"
    name = "Hugo Tailwindcss Starter"
    description = "A simple bootstraped theme for Hugo, build with Tailwindcss."

    favicon = "favicon.ico"

    # Sections displayed in the footer
    mainSections = ['products', 'services', 'blog']

    [params.socials]
      facebook = "https://facebook.com/something"
      instagram = "#"
      x = "#"
      linkedin = "#"
      youtube = "#"

    [params.footer]

      [params.footer.contactInfo]
        title   = "Contact"
        address = "713 Elmwood St. Prior Lake, MN 55372"
        phone   = "409-896-1444"
        email   = "info@roxo.co"


# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
